theme: jekyll-theme-cayman

<!DOCTYPE html>
<html lang="en">

<head>
  <title>Web Mapping Tutorial 1</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.16/p5.min.js" type="text/javascript"></script>
  <script src="https://unpkg.com/mappa-mundi/dist/mappa.js" type="text/javascript"></script>
</head>

<body>
  <script>
  let myMap;
let canvas;
const mappa = new Mappa('Leaflet');
const options = {
  lat: 49,
  lng: -123,
  zoom: 3,
  style: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
}

function setup(){
  canvas = createCanvas(640,640);
  myMap = mappa.tileMap(options);
  myMap.overlay(canvas)
  meteorites = loadTable('https://raw.githubusercontent.com/cvalenzuela/Mappa/master/tutorials/basic/Meteorite_Landings.csv', 'csv', 'header');
  myMap.onChange(drawMeteorites);
  fill(214, 81, 81);
  stroke(138, 26, 26);
}

function draw(){
}

function drawMeteorites() {
  clear();

  for (let i = 0; i < meteorites.getRowCount(); i++) {
    const latitude = Number(meteorites.getString(i, 'reclat'));
    const longitude = Number(meteorites.getString(i, 'reclong'));
    if (myMap.map.getBounds().contains({lat: latitude, lng: longitude})) {
      const pos = myMap.latLngToPixel(latitude, longitude);
      let size = meteorites.getString(i, 'mass (g)');
      size = map(size, 558, 60000000, 1, 25) + myMap.zoom();
      ellipse(pos.x, pos.y, size, size);
      //rect(pos.x, pos.y, size, size); //Code written but no cartographic improvements from it
    }
  }
}
  </script>
</body>

</html>
